### ISSUE TITLE
Event loop is not closed properly after running pytest

### ISSUE THREAD

**Issue by dolamroth** [DmitryBurnaev/starlette-web#6]
RuntimeError is raised after successfully running all tests

```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000001E005AB7DC0>
Traceback (most recent call last):
  File "...\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "...\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "...\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "...\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

**Comment by DmitryBurnaev** [comment]
It seems like local problem. I can't reproduce this kind of error(
Could you please try to run tests inside the docker container? Something like:
1. `cp .env.local .env`
2. provide env variables in `.env` file
3. run tests
```bash
docker image build -t starlette-web . && docker run -ti --env-file .env --rm starlette-web
```

**Comment by dolamroth** [comment]
It is Windows-specific error https://github.com/pytest-dev/pytest-asyncio/issues/371
I'll try to deal with it later

**Comment by dolamroth** [comment]
Solved in https://github.com/DmitryBurnaev/starlette-web/pull/54
